spring.application.name=Gateway

# Rota para o serviço de Usuários
spring.cloud.gateway.routes[0].id=user-service
spring.cloud.gateway.routes[0].uri=lb://user
spring.cloud.gateway.routes[0].predicates[0]=Path=/user/**

# Rota para o serviço de Produtos
spring.cloud.gateway.routes[1].id=product-service
spring.cloud.gateway.routes[1].uri=lb://Product
spring.cloud.gateway.routes[1].predicates[0]=Path=/product/**

# Rota para o serviço de Pedidos
spring.cloud.gateway.routes[2].id=order-service
spring.cloud.gateway.routes[2].uri=lb://order
spring.cloud.gateway.routes[2].predicates[0]=Path=/order/**

# Rota para o serviço de Estoque
spring.cloud.gateway.routes[3].id=inventory-service
spring.cloud.gateway.routes[3].uri=lb://inventory
spring.cloud.gateway.routes[3].predicates[0]=Path=/inventory/**

# Rota para o serviço de Pagamentos
spring.cloud.gateway.routes[4].id=payment-service
spring.cloud.gateway.routes[4].uri=lb://payments
spring.cloud.gateway.routes[4].predicates[0]=Path=/payments/**
